In [76]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [77]:
fake_df = pd.read_csv("1Fake.csv")
true_df = pd.read_csv("2True.csv")

In [78]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [79]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [80]:
fake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [81]:
true_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

In [82]:
fake_df["class"] = 0
true_df["class"] = 1

In [83]:
true_df.shape

(21417, 5)

In [84]:
fake_df.shape

(23481, 5)

In [85]:
manualtesting_df = pd.read_csv("4manual_testing.csv")

In [86]:
for i in range(23480,23470,-1):
    fake_df.drop([i],axis = 0, inplace = True)

for i in range(21416,21406,-1):
    true_df.drop([i],axis = 0, inplace = True)

In [87]:
manualtesting_df.head()

,Unnamed: 0,title,text,subject,date,class
0,23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
1,23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
2,23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
3,23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
4,23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0

In [88]:
data_df = pd.concat([fake_df,true_df],axis=0)
data_df.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [89]:
data = data_df.drop(['title','subject','date'],axis=1)

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44878 entries, 0 to 21406
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    44878 non-null  object
 1   class   44878 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.0+ MB

In [91]:
data = data.sample(frac = 1)

In [92]:
data.head()

                                                    text  class
19684  GENEVA (Reuters) - U.N. investigators have sta...      1
2996   WASHINGTON (Reuters) - U.S. Vice President Mik...      1
5730   BOGOTA (Reuters) - Nobel Peace Prize winners m...      1
866    An interview with CNN anchor Anderson Cooper a...      0
11136  During Obama s 8 years in office, he took a pa...      0

In [93]:
data.reset_index(inplace=True)
data.drop(['index'],axis = 1,inplace =True)

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44878 entries, 0 to 44877
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    44878 non-null  object
 1   class   44878 non-null  int64
dtypes: int64(1), object(1)
memory usage: 701.3+ KB

In [95]:
data

                                                    text  class
0      GENEVA (Reuters) - U.N. investigators have sta...      1
1      WASHINGTON (Reuters) - U.S. Vice President Mik...      1
2      BOGOTA (Reuters) - Nobel Peace Prize winners m...      1
3      An interview with CNN anchor Anderson Cooper a...      0
4      During Obama s 8 years in office, he took a pa...      0
...                                                  ...    ...
44873  It s no secret Americans have been demonstrati...      0
44874  ANKARA/BAGHDAD/ERBIL, Iraq (Reuters) - Iraqi t...      1
44875  The Trump administration likes to keep their b...      0
44876  21st Century Wire says While America s politic...      0
44877  RIYADH (Reuters) - U.S. President Barack Obama...      1

[44878 rows x 2 columns]

Preprocessing text. removeing extra space,special chr,url and links and covert to lowercase

In [96]:
import re
import string
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]','',text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+','',text)
    text = re.sub('<.*?>+',b'',text)
    text = re.sub('[%s]' % re.escape(string.punctuation),'',text)
    text = re.sub('\w*\d\w*','',text)
    return text

<>:5: SyntaxWarning: invalid escape sequence '\['
<>:7: SyntaxWarning: invalid escape sequence '\S'
<>:10: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\['
<>:7: SyntaxWarning: invalid escape sequence '\S'
<>:10: SyntaxWarning: invalid escape sequence '\w'
C:\Users\DELL\AppData\Local\Temp\ipykernel_4000\320411231.py:5: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[.*?\]','',text)
C:\Users\DELL\AppData\Local\Temp\ipykernel_4000\320411231.py:7: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub('https?://\S+|www\.\S+','',text)
C:\Users\DELL\AppData\Local\Temp\ipykernel_4000\320411231.py:10: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*','',text)

In [97]:
data["text"] = data["text"].apply(wordopt)

word to vector conversion

import nltk...
nltk.download('punkt')...
from nltk.tokenize import word_tokenize...
data["text] = data["text"].apply(word_tokenize)...
DIDN'T WORK

In [98]:
#DIDN'T WORK
# import nltk
# nltk.download('punkt')
# from nltk.tokenize import word_tokenize
# # data["tokens"] = data["text"].apply(word_tokenize)
# x = "my name is abc. nice to meet you. how are you?"
# word_tokenize(x)

Tokenization

In [ ]:
#import spacy
#nlp = spacy.load('en_core_web_sm')

In [ ]:
#data["tokens"] = data["text"].apply(lambda x: [token.text for token in nlp(x)])
#done ....take 50mins

In [ ]:
data
#data after tokenization

,text,class,tokens
0,a caller to british radio host katie hopkins w...,0,"[a, caller, to, british, radio, host, katie, h..."
1,london reuters european union lawmakers on...,1,"[london, , reuters, , european, union, law..."
2,washington reuters president barack obama ...,1,"[washington, , reuters, , president, barac..."
3,berlin reuters five top german politicians...,1,"[berlin, , reuters, , five, top, german, p..."
4,oh the irony of a terror attack by muslims tak...,0,"[oh, the, irony, of, a, terror, attack, by, mu..."
...,...,...,...
44873,washington reuters criminal justice reform...,1,"[washington, , reuters, , criminal, justic..."
44874,washington reuters donald trump s campaign...,1,"[washington, , reuters, , donald, trump, s..."
44875,the national archives inspector general invest...,0,"[the, national, archives, inspector, general, ..."
44876,washington reuters democratic presidential...,1,"[washington, , reuters, , democratic, pres..."
44877,ankara reuters turkey may reciprocate a mo...,1,"[ankara, , reuters, , turkey, may, recipro..."

In [ ]:
#data.to_csv('tokenizedData.csv',index=False)

to upload the tokenized data upload it rather than long computation again and again.
data = pd.read_csv("tokenizedData.csv")

In [ ]:
sentences = data["tokens"].tolist()

Version Conficts
Project A uses spaCy + NumPy 2.2
Project B uses gensim + NumPy 1.26